name: "[player] Run tests"

on:
  # runs on pushes to branch
  push:
    branches: ["main"]
  # allow running manually from the actions tab
  workflow_dispatch:

# allow only one concurrent deployment on the same wf-branch combo, cancel in-progress
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
 run:
  working-directory: ./packages/player

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # prepare env
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      # run tasks
      - name: Build
        run: pnpm run build
      - name: Test
        run: pnpm run test
